### PR TITLE
fix for Issues #10, #8

### PR DESCRIPTION
**Pull request by fgn-git-hub**

### CODE REVIEW

**Comment by lsteeger** [comment]
This looks like a fix for #14 as well. A pull would be nice. The ineffective buttons are annoying.

**Comment by dol** [comment]
Any possibility to release/test this fix? The extension is broken at the moment.

**Comment by jobisoft** [comment]
We have moved in a different direction and this PR no longer applies. Can you check if the issues fixed by this are fixed in the latest release?

https://github.com/Extended-Thunder/folder-pane-view-switcher/releases/tag/v5.2

**Comment by arndissler** [comment]
Thanks to the @fgn-git-hub and @lsteeger who put the effort in this PR. But as @jobisoft mentioned, it's slightly outdated. If the issues still apply to the new release, please let me know in the issue section.

**Pull request closed without merging**
