### PR TITLE
Update messages.json (en-US)

### PR DESCRIPTION
**Pull request by DenB10**

### CODE REVIEW

**Comment by jikamens** [comment]
It would be better if you (a) put these changes in a single pull request instead of a bunch of separate ones and (b) included more descriptive commit messages than just "Update <filename>." The first line of the commit message should be a short summary of what's changing, and then a blank line, and then subsequent lines should include more detail if necessary, but "Update <filename>" definitely isn't enough detail.

**Comment by jikamens** [comment]
To be clear, if the changes are logically distinct then they should be in separate _commits_, but you don't need to submit all of those commits in separate PRs; you can include them all on the same branch and submit that branch in a single PR.

**Comment by jikamens** [comment]
(And allow me to add what I should have said first: thank you for contributing to this project! We appreciate it. Sorry for not leading with that; I'm a bit frazzled today and not handling interrupts well as a result.)

**Comment by DenB10** [comment]
I'm sorry I didn't do things by the book. I thought about putting everything in one PR but I don't know how to do it.

On the other hand, you're right, I should have provided more explanations. My original intention was simply to update the French translation. Then I realized that some words weren't translatable in the options page, so I made a few additions to the options.js and options.html files...

Tell me how to make a single PR and I'll do it (I haven't installed the Github software though). Alternatively, I can send you the whole thing as a zip file.

As for courtesy messages, it doesn't matter :smile:

**Comment by jikamens** [comment]
I can try to help though my time is limited. To start with, can you tell me how you created these pull requests? I suspect the workflow you used is not the same as the one I would normally use so I need to understand where we're starting from to be able to point you in the right direction.

**Comment by DenB10** [comment]
I don't want to waste your time. If you don't have time, I'll close the PR and that's it.
To put it simply:
1. I've created a fork of your repository.
2. I edited the file I wanted to modify and clicked on the buttons proposed by my browser: "Commit changes" then "Create a PR".

**Comment by jikamens** [comment]
Got it. We'll work with what you submitted, don't worry about it. That'll be easier for both of us. ;-) Thank you again for contributing!

**Comment by DenB10** [comment]
No feedback, I close.

**Comment by arndissler** [comment]
Sorry for being late to the party – I accidentally missed the notification for the PRs.

**Comment by arndissler** [comment]
Reformatted the language file, PR accepted. Thanks for contributing!

**Pull request merged**
