### PR TITLE
Basic Thunderbird v115 supernova support

### PR DESCRIPTION
**Pull request by arndissler**
The changes will restore the functionality for the shortcuts and the folder header pane buttons for Thunderbird v115.

Missing features in v115/supernova:
- drag'n'drop support for messages to the folder pane
- removal of menu entries for the folder pane view modes

### CODE REVIEW

**Comment by lsteeger** [comment]
Using:

Thunderbird 115.1.0 (64-bit)
SUPERNOVA
Mozilla Thunderbird for Manjaro Linux
Manjaro 1.0

I locally built this addon as follows:

gh repo clone Extended-Thunder/folder-pane-view-switcher                                                                        
<code>
  cloning into 'folder-pane-view-switcher'...
  remote: Enumerating objects: 1334, done.
  remote: Counting objects: 100% (24/24), done.
  remote: Compressing objects: 100% (17/17), done.
  remote: Total 1334 (delta 7), reused 17 (delta 5), pack-reused 1310
  Receiving objects: 100% (1334/1334), 336.35 KiB | 3.08 MiB/s, done.
  Resolving deltas: 100% (722/722), done.
</code>
cd folder-pane-view-switcher/                                                                                                   

gh pr list                                                                                                                      
<code>
Showing 4 of 4 open pull requests in Extended-Thunder/folder-pane-view-switcher

#30  Basic Thunderbird v115 supernova support                    
        arndissler:feat/thunderbird-v115  about 2 hours ago
#28  Use Services global variable
         arai-a:services-global            about 1 month ago
#27  fix: compact view isn't respected when switching folder panes
         fix/compact-view                  about 7 months ago
#13  fix for Issues #10, #8
         Br_vr_78                          about 2 years ago
</code>

gh pr checkout 13 
<code>
ranch 'Br_vr_78' set up to track 'origin/Br_vr_78'.
Switched to a new branch 'Br_vr_78'
</code>                                                                                                     

gh pr checkout 27                                                                                                               
<code>
branch 'fix/compact-view' set up to track 'origin/fix/compact-view'.
Switched to a new branch 'fix/compact-view'
</code>

gh pr checkout 28                                                                                                               
<code>
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 5 (delta 2), pack-reused 0
Unpacking objects: 100% (5/5), 641 bytes | 213.00 KiB/s, done.
From https://github.com/Extended-Thunder/folder-pane-view-switcher
 * [new ref]         refs/pull/28/head -> services-global
Switched to branch 'services-global'
</code>

gh pr checkout 30                                                                                                               
<code>
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 56 (delta 28), reused 53 (delta 27), pack-reused 0
Unpacking objects: 100% (56/56), 24.50 KiB | 597.00 KiB/s, done.
From https://github.com/Extended-Thunder/folder-pane-view-switcher
 * [new ref]         refs/pull/30/head -> feat/thunderbird-v115
Switched to branch 'feat/thunderbird-v115'
</code>

make
<code>
rm -f FolderPaneSwitcher.xpi.tmp
zip -r FolderPaneSwitcher.xpi.tmp ./popup/index.js ./popup/index.css ./popup/installed.html ./popup/update.html ./LICENSE ./api/FPVS/implementation.js ./api/FPVS/schema.json ./api/LegacyMenu/implementation.js ./api/LegacyMenu/schema.json ./utils/index.js ./_locales/en-US/messages.json ./_locales/de-DE/messages.json ./_locales/nl/messages.json ./_locales/fr/messages.json ./_locales/zh-CN/messages.json ./manifest.json ./background.html ./icon.png ./background.js ./content/options.html ./content/options.js ./content/right-arrow.png ./content/left-arrow.png ./content/options.css
  adding: popup/index.js (deflated 55%)
  adding: popup/index.css (deflated 54%)
  adding: popup/installed.html (deflated 62%)
  adding: popup/update.html (deflated 62%)
  adding: LICENSE (deflated 67%)
  adding: api/FPVS/implementation.js (deflated 81%)
  adding: api/FPVS/schema.json (deflated 91%)
  adding: api/LegacyMenu/implementation.js (deflated 85%)
  adding: api/LegacyMenu/schema.json (deflated 84%)
  adding: utils/index.js (deflated 62%)
  adding: _locales/en-US/messages.json (deflated 78%)
  adding: _locales/de-DE/messages.json (deflated 58%)
  adding: _locales/nl/messages.json (deflated 51%)
  adding: _locales/fr/messages.json (deflated 48%)
  adding: _locales/zh-CN/messages.json (deflated 47%)
  adding: manifest.json (deflated 69%)
  adding: background.html (deflated 26%)
  adding: icon.png (stored 0%)
  adding: background.js (deflated 80%)
  adding: content/options.html (deflated 76%)
  adding: content/options.js (deflated 77%)
  adding: content/right-arrow.png (deflated 0%)
  adding: content/left-arrow.png (deflated 0%)
  adding: content/options.css (deflated 35%)
mv FolderPaneSwitcher.xpi.tmp FolderPaneSwitcher.xpi
</code>

Made sure prior verson of addon was removed.

Restarted Thunderbird.

Installed FolderPaneSwitcher.xpi from Manage Your Extensions -> Install Add-on from File...

Restarted Thundebird.

Folder Panel Switcher arrows appear and work! 

From Manage Your Extensions -> Folder Pane View Switch -> Add-on Options

The options.html page appears.

Unchecked the Arrows boxes for the views I do not want.

Clicked OK, but the page does not close and no options are saved.

Close the options.html page tab.

Restarted Thunderbird.

Revisited options.html and no options have been changed.

Almost there!

**Comment by arndissler** [comment]
Thanks for testing so far, @lsteeger - I'll fix the remaining issues over the next days. 

→ The others who made it here: the PR is still in _draft_ mode and **not** ready for production use and as it is under construction.

`<insert digging worker gif here>`

**Comment by arndissler** [comment]
@lsteeger: you can give the branch another try, if you find the time. The options page should now work as expected.

There's still one main glitch for v115: when a new window is opened, the buttons might not be correctly created. Switching back and forth to another space fixes this.

**Comment by lsteeger** [comment]
The latest draft works great!  Options are now saved!

I have an enhancement request that would make where you are visible in the arrow tooltips:

Left arrow tooltip text before:

Previous Folder Pane - Before

Left arrow tooltip text after:

Previous Folder Pane - Enhanced

Right arrow tooltip text before:

Next Folder Pane - Before

Right arrow tooltip text after:

Next Folder Pane - Enhanced

p.s.

I used [simplescreenrecorder](https://www.maartenbaert.be/simplescreenrecorder/) [fixed rectangle], [vlc](https://www.videolan.org/vlc/) [take snapshot] and [gimp](https://www.gimp.org/) [color picker, rectangle select, bucket fill and text tools] to create the above samples.

lrs.

**Comment by arndissler** [comment]
**Current status for supernova:**
- arrows are toggable
- menu items are toggable
- panes can be switched by arrows and shortcuts
- options tab works as expected

**Known differences to v102 that will be reworked on another PR:**
- Drag'n'drop doesn't work in supernova
- when opening a new Thunderbird window, it could happen that the arrows are not shown and menus are still visible

@jikamens Would you please give it a quick check and review?

**Comment by lsteeger** [comment]
I installed the latest changes.

An old bug has returned.  The arrows don't appear after completely stopping TB and starting it again.

If I go to the options page and click Ok, they reappear.

Also, the Cancel and Reset button text has shifted to the right and is parttially truncated. 
Screenshot_2023-08-27_17-49-50

**Comment by arndissler** [comment]
First of all: thanks @lsteeger for having a look!

> An old bug has returned. The arrows don't appear after completely stopping TB and starting it again.

I'll check this.


> Also, the Cancel and Reset button text has shifted to the right and is partially truncated. 

That's strange. Is it still Thunderbird v115.1.10 (64bit) on Manjaro?

**Comment by lsteeger** [comment]
Did you mean:

Is it still Thunderbird v115.1.`0` (64bit) on Manjaro?

Still running:

Thunderbird 115.1.0 (64-bit)
SUPERNOVA
Mozilla Thunderbird for Manjaro Linux
Manjaro 1.0

**Comment by arndissler** [comment]
@lsteeger Fixed: UI is now correctly set up on Thunderbird restart and when opening a new window

**Comment by lsteeger** [comment]
Confirmed. Arrows now appear at startup again!

On the 'Cancel' and 'Reset' button text, I switched themes just in case it was theme-related, but no change in any theme.  The text on these two buttons is still shifted to the right.

By the way the options page does not follow the overall theme colors.

**Comment by jikamens** [comment]
I take it from the fact that you just put out a release that I don't need to review this anymore?

Sorry about the delay, I've been neck deep in Send Later stuff.

**Pull request merged**
